accounts/urls.py
from django.urls import path

from .views import (
    AccountCreateDoneView,
    AccountCreateView,
    AccountReadPrivateView,
    AccountReadPublicView,
    AccountUpdateView,
    HomeView,
    LogoutView,
    SiteAccessURLRequestDoneView,
    SiteAccessURLRequestView,
    TokenRevocationFailedView,
    TokenRevocationURLRequestDoneView,
    TokenRevocationURLRequestView,
    TokenRevocationView,
)

app_name = "accounts"
urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("invite/", AccountCreateView.as_view(), name="account_create"),
    path("invite/done/", AccountCreateDoneView.as_view(), name="account_create_done"),
    path("login/", SiteAccessURLRequestView.as_view(), name="site_access_url_request"),
    path(
        "login/done/",
        SiteAccessURLRequestDoneView.as_view(),
        name="site_access_url_request_done",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("me/", AccountReadPrivateView.as_view(), name="account_read_private"),
    path("me/update/", AccountUpdateView.as_view(), name="account_update"),
    path(
        "token/revoke/",
        TokenRevocationURLRequestView.as_view(),
        name="token_revocation_url_request",
    ),
    path(
        "token/revoke/done/",
        TokenRevocationURLRequestDoneView.as_view(),
        name="token_revocation_url_request_done",
    ),
    path(
        "token/revoke/confirm/failed/",
        TokenRevocationFailedView.as_view(),
        name="token_revocation_failed",
    ),
    path(
        "token/revoke/<str:revocation_token>/confirm/",
        TokenRevocationView.as_view(),
        name="token_revocation",
    ),
    path(
        "user/<uuid:pk>/", AccountReadPublicView.as_view(), name="account_read_public"
    ),
]

email_responses/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

accounts/models.py
import uuid

from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from . import utils
from .managers import UserManager


class Invite(models.Model):
    created_at = models.DateTimeField(_("creation time"), default=utils.get_utc_now)
    recipient = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="invites_from_me",
    )

    def __str__(self):
        return f"{self.sender} invites {self.recipient}"


class User(AbstractBaseUser, PermissionsMixin):
    uuid = models.UUIDField(
        _("UUID"), default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )
    created_at = models.DateTimeField(_("creation time"), default=utils.get_utc_now)
    email = models.EmailField(_("email address"), unique=True)
    name = models.CharField(_("name"), max_length=64)
    is_active = models.BooleanField(_("active"), default=True)
    is_staff = models.BooleanField(_("staff status"), default=False)
    password_last_set_at = models.DateTimeField(
        _("password last set at"), default=utils.get_utc_now
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        swappable = "AUTH_USER_MODEL"

    def __str__(self):
        return f"<{self.email}>"

    def get_absolute_url(self):
        return reverse("accounts:account_read_public", kwargs={"pk": self.pk})

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, logout, update_session_auth_hash
from django.forms.models import ModelForm

from . import exceptions, message_codes, services, tokens, utils

UserModel = get_user_model()


class AccountCreationForm(forms.ModelForm):
    class Meta:
        fields = ["name", "email"]
        model = UserModel

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        created_user = super().save(commit=commit)
        services.record_invite(inviter=self.request.user, invitee=created_user)
        services.send_site_access_url(recipient=created_user, first_time_user=True)
        messages.success(self.request, message_codes.ACCOUNT_CREATE_SUCCEEDED)
        return created_user


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        fields = ["name"]
        model = UserModel


class AdminAccountUpdateForm(ModelForm):
    class Meta:
        model = UserModel
        fields = [
            "name",
            "is_active",
            "is_staff",
            "is_superuser",
            "groups",
            "user_permissions",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user_permissions = self.fields.get("user_permissions")
        if user_permissions:
            user_permissions.queryset = user_permissions.queryset.select_related(
                "content_type"
            )


class LoginForm(forms.Form):
    email = forms.EmailField(help_text="Email address")

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def send_site_access_url(self):
        email = self.cleaned_data["email"]
        try:
            user = UserModel.objects.get(email=email)
        except UserModel.DoesNotExist:
            user = None

        if user is not None:
            services.send_site_access_url(
                recipient=user, next_url=self.request.GET.get("next")
            )

        messages.success(self.request, message_codes.SITE_ACCESS_URL_REQUEST_SUCCEEDED)


class LogoutForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def logout(self):
        logout(self.request)
        messages.success(self.request, message_codes.LOGOUT_SUCCEEDED)


class TokenRevocationURLRequestForm(forms.Form):
    email = forms.EmailField(help_text="Email address")

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def send_token_revocation_url(self):
        email = self.cleaned_data["email"]
        try:
            user = UserModel.objects.get(email=email)
        except UserModel.DoesNotExist:
            user = None

        if user is not None:
            services.send_token_revocation_url(recipient=user)

        messages.success(self.request, message_codes.TOKEN_REVOKE_URL_REQUEST_SUCCEEDED)


class TokenRevocationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        self.revocation_token = kwargs.pop("revocation_token")
        super().__init__(*args, **kwargs)

    def revoke_token(self):
        token_owner = tokens.get_token_owner(
            token=self.revocation_token,
            token_generator=tokens.token_revocation_token_generator,
            max_age=settings.REVOCATION_TOKEN_MAX_AGE,
        )
        if token_owner is None:
            messages.error(self.request, message_codes.TOKEN_REVOCATION_FAILED)
            raise exceptions.BadTokenException

        # evaluate and cache auth user
        # for updating session hash after password change
        auth_user = self.request.user or None
        token_owner.set_password(utils.generate_random_password())
        token_owner.password_last_set_at = utils.get_utc_now()
        token_owner.save()

        if token_owner == auth_user:
            update_session_auth_hash(self.request, token_owner)

        messages.success(self.request, message_codes.TOKEN_REVOCATION_SUCCEEDED)

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    FormView,
    TemplateView,
    UpdateView,
)

from .exceptions import BadTokenException
from .forms import (
    AccountCreationForm,
    AccountUpdateForm,
    LoginForm,
    LogoutForm,
    TokenRevocationForm,
    TokenRevocationURLRequestForm,
)

UserModel = get_user_model()


class AccountCreateView(CreateView):
    model = UserModel
    form_class = AccountCreationForm
    success_url = reverse_lazy("accounts:account_create_done")
    template_name = "accounts/account_create.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class AccountCreateDoneView(TemplateView):
    template_name = "accounts/account_create_done.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class AccountReadPrivateView(LoginRequiredMixin, TemplateView):
    queryset = UserModel.objects.select_related("invite__sender")
    template_name = "accounts/account_read_private.html"

    def get_user(self):
        try:
            obj = self.queryset.get(pk=self.request.user.pk)
        except self.queryset.model.DoesNotExist:
            raise Http404

        return obj

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["user"] = context_data["object"] = self.get_user()
        return context_data


class AccountReadPublicView(DetailView):
    queryset = UserModel.objects.select_related("invite__sender")
    template_name = "accounts/account_read_public.html"


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    form_class = AccountUpdateForm
    success_url = reverse_lazy("accounts:account_read_private")
    template_name = "accounts/account_update.html"

    def get_object(self, queryset=None):
        return self.request.user


class HomeView(TemplateView):
    template_name = "accounts/home.html"


class LogoutView(FormView):
    form_class = LogoutForm
    success_url = reverse_lazy("accounts:site_access_url_request")
    template_name = "accounts/logout.html"

    def form_valid(self, form):
        form.logout()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class SiteAccessURLRequestView(FormView):
    form_class = LoginForm
    success_url = reverse_lazy("accounts:site_access_url_request_done")
    template_name = "accounts/site_access_url_request.html"

    def form_valid(self, form):
        form.send_site_access_url()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class SiteAccessURLRequestDoneView(TemplateView):
    template_name = "accounts/site_access_url_request_done.html"


class TokenRevocationURLRequestView(FormView):
    form_class = TokenRevocationURLRequestForm
    success_url = reverse_lazy("accounts:token_revocation_url_request_done")
    template_name = "accounts/token_revocation_url_request.html"

    def form_valid(self, form):
        form.send_token_revocation_url()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class TokenRevocationURLRequestDoneView(TemplateView):
    template_name = "accounts/token_revocation_url_request_done.html"


class TokenRevocationView(FormView):
    form_class = TokenRevocationForm
    success_url = reverse_lazy("accounts:home")
    template_name = "accounts/token_revocation.html"

    def form_valid(self, form):
        try:
            form.revoke_token()
        except BadTokenException:
            return HttpResponseRedirect(reverse("accounts:token_revocation_failed"))

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        kwargs["revocation_token"] = self.kwargs["revocation_token"]
        return kwargs


class TokenRevocationFailedView(TemplateView):
    template_name = "accounts/token_revocation_failed.html"

accounts/templates/accounts/account_create.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/account_create.css' %}">
{% endblock %}

{% block title %}{% translate "Invite user" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">

                <h1>{% translate "Invite User" %}</h1>

                <form method="post">
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {{ form.non_field_errors }}

                    <div class="input-field">
                        <i class="material-icons prefix">account_circle</i>
                        <input
                            class="validate"
                            id="name"
                            maxlength="{{ form.name.field.max_length }}"
                            name="name"
                            type="text"
                            {% if form.name.value != None %}value="{{ form.name.value|stringformat:'s' }}"{% endif %}
                            required>
                        <label for="name">{% translate "Fullname" %}</label>

                        {% if form.name.errors %}
                        <ul class="errors">
                            {% for error in form.name.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    <div class="input-field">
                        <i class="material-icons prefix">email</i>
                        <input
                            class="validate"
                            id="email"
                            maxlength="{{ form.email.field.max_length }}"
                            name="email"
                            type="email"
                            {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}"{% endif %}
                            required>
                        <label for="email">{% translate "Email" %}</label>

                        {% if form.email.errors %}
                        <ul class="errors">
                            {% for error in form.email.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                    <div class="actions">
                        <button class="btn waves-effect waves-light"><i class="material-icons left">send</i>{% translate "Send Invite" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/account_create_done.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/account_create_done.css' %}">
{% endblock %}

{% block title %}{% translate "Invite sent" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">

                {% if messages %}
                    {% for message in messages %}
                        {% include "dismissible_alert.html" with message=message %}
                    {% endfor %}
                {% endif %}

                <div class="icon-holder">
                    <img class="icon md" src="{% static 'img/mark_email_read_black_48dp.svg' %}" alt="">
                </div>

                <h1>{% translate "Invite Sent!" %}</h1>

                <p>{% translate "Please ask the invitee to check their inbox." %}</p>

                <div class="actions">
                    <a href="{% url 'accounts:account_create' %}" class="waves-effect waves-light btn">{% translate 'Invite another person' %}</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/account_read_private.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/account_read_private.css' %}">
{% endblock %}

{% block title %}{% translate "My profile" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2 l10 offset-l1">

                {% if messages %}
                    {% for message in messages %}
                        {% include "dismissible_alert.html" with message=message %}
                    {% endfor %}
                {% endif %}

                <h1>{{ user.name }}</h1>

                {% if user.invite.sender %}
                    <p>
                        <b>{% translate "Invited by" %}:</b>
                        <a href="{{ user.invite.sender.get_absolute_url }}">{{ user.invite.sender.name }}</a>
                    </p>
                    <p>
                        <b>{% translate "Invited on" %}:</b>
                        {{ user.invite.created_at|date:"F d, Y" }}
                    </p>
                {% endif %}
                <p>
                    <b>{% translate "Joined on" %}:</b>
                    {{ user.created_at|date:"F d, Y" }}
                </p>

                <div class="section">
                    <h2>{% translate "Account" %}</h2>
                    <div class="actions">
                        <a href="{{ user.get_absolute_url }}" class="waves-effect waves-light btn">{% translate "My public profile" %}</a>
                        <a href="{% url 'accounts:account_update'  %}" class="waves-effect waves-light btn">{% translate "Edit my profile" %}</a>
                    </div>
                </div>

                <div class="section">
                    <h2>{% translate "Tokens" %}</h2>
                    <div class="actions">
                        <a href="{% url 'accounts:token_revocation_url_request' %}" class="waves-effect waves-light btn">{% translate "Revoke my tokens" %}</a>
                    </div>
                </div>

                {% if request.user.is_superuser %}
                <div class="section">
                    <h2>{% translate "Invite User" %}</h2>
                    <div class="actions">
                        <a href="{% url 'accounts:account_create' %}" class="waves-effect waves-light btn">{% translate "Invite user" %}</a>
                    </div>
                </div>
                {% endif %}

                <div class="section">
                    <h2>{% translate "Authentication" %}</h2>
                    <div class="actions">
                        <a href="{% url 'accounts:logout' %}" class="waves-effect waves-light btn">{% translate "Logout" %}</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/account_read_public.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/account_read_public.css' %}">
{% endblock %}

{% block title %}{% translate "User profile" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2 l10 offset-l1">

                {% if messages %}
                    {% for message in messages %}
                        {% include "dismissible_alert.html" with message=message %}
                    {% endfor %}
                {% endif %}
                
                <h1>{{ user.name }}</h1>
                {% if user.invite.sender %}
                    <p><b>Invited by:</b> <a href="{{ user.invite.sender.get_absolute_url }}">{{ user.invite.sender.name }}</a></p>
                {% endif %}
                <p><b>Joined:</b> {{ user.created_at|date:"F Y" }}</p>

                {% if request.user.is_authenticated  and request.user.pk == user.pk %}
                    <div class="actions">
                        <a href="{% url 'accounts:account_update'  %}" class="waves-effect waves-light btn">{% translate "Edit my profile" %}</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/account_update.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/account_update.css' %}">
{% endblock %}

{% block title %}{% translate "Update account" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section class="container">
    <div class="row">
        <div class="col m8 offset-m2">

            <h1>{% translate "Update Your Profile" %}</h1>

            <form method="post">
                {% csrf_token %}

                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {{ form.non_field_errors }}

                <div class="input-field">
                    <i class="material-icons prefix">person</i>
                    <input
                        class="validate"
                        id="name"
                        maxlength="{{ form.name.field.max_length }}"
                        name="name"
                        type="text"
                        {% if form.name.value != None %}value="{{ form.name.value|stringformat:'s' }}"{% endif %}
                        required>
                    <label for="name">{% translate "Name" %}</label>

                    {% if form.name.errors %}
                    <ul class="errors">
                        {% for error in form.name.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="actions">
                    <button class="btn waves-effect waves-light">{% translate "Update Profile" %}</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/home.css' %}">
{% endblock %}

{% block title %}{% translate "Home" %} &mdash; {{ block.super }} {% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">
                {% if messages %}
                    {% for message in messages %}
                        {% include "dismissible_alert.html" with message=message %}
                    {% endfor %}
                {% endif %}

                {% if not request.user.is_authenticated %}
                    <h1>Hey there!</h1>
                    <h2>Welcome to {{ request.site.name }}.</h2>
                    <p>Please <a href="{% url 'accounts:site_access_url_request' %}">Log in to your account</a> to continute using {{ request.site.name }}.</p>
                    <p>If you don't have an account yet, please contact the admin to send you an invite.</p>
                    <p>Warm regards,</p>
                    <p>The {{ request.site.name }} Team.</p>
                {% else %}
                    <h1>Hello {{ request.user.name }}!</h1>
                    <h2>Welcome to {{ request.site.name }}.</h2>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/logout.css' %}">
{% endblock %}

{% block title %}{% translate "Logout" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">

                <h1>{% translate "Logout" %}</h1>

                <form method="post">
                    {% csrf_token %}

                    <div class="actions">
                        <button class="btn waves-effect waves-light">{% translate "Logout" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/site_access_url_request_done.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/site_access_url_request_done.css' %}">
{% endblock %}

{% block title %}{% translate "Login link sent" %} &mdash; {{ block.super }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">

                {% if messages %}
                    {% for message in messages %}
                        {% include "dismissible_alert.html" with message=message %}
                    {% endfor %}
                {% endif %}

                <div class="icon-holder">
                    <img class="icon md" src="{% static 'img/vpn_key_black_48dp.svg' %}" alt="">
                </div>
                
                <h1>{% translate "Magic Login Link Sent!" %}</h1>

                <div>
                    {% blocktranslate %}
                    <p>Please check your mail.<br>We've just sent you a magic link to login to this site with your account.</p>
                    <p>Kind wait for up to 4 minutes if you don't get the mail immediately.<br>And don't forget to check your spam while you're at it.</p>
                    {% endblocktranslate %}
                    <div class="jumbotron">
                        {% blocktranslate %}
                        <h2 class="mt-0">Still did not get a mail?</h2>
                        <p>Please confirm that you <em>really</em> have an account on this site with the email you're asking that the magic login link be sent to.</p>
                        {% endblocktranslate %}
                        <div class="actions">
                            <a href="{% url 'accounts:site_access_url_request' %}" class="waves-effect waves-light btn">{% translate "Request magic link, again" %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/token_revocation_failed.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% translate "Token revocation failed" %} &mdash; {{ block.super }}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/token_revocation_failed.css' %}">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">

                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            {% include "dismissible_alert.html" with message=message %}
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="icon-holder">
                    <img class="icon md" src="{% static 'img/error_feedback_black_48dp.svg' %}" alt="">
                </div>

                <h1>{% translate "Token Revocation Failed!" %}</h1>

                <p>{% translate "Your token revocation link is either invalid or expired." %}</p>
                <p>{% translate " Please request a fresh one." %}</p>

                <div class="actions">
                    <a href="{% url 'accounts:token_revocation_url_request' %}" class="waves-effect waves-light btn">{% translate "Request Link" %}</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/token_revocation_url_request_done.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% translate "Token revocation link sent" %} &mdash; {{ block.super }}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/token_revocation_url_request_done.css' %}">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">

                {% if messages %}
                    {% for message in messages %}
                        {% include "dismissible_alert.html" with message=message %}
                    {% endfor %}
                {% endif %}

                <div class="icon-holder">
                    <img class="icon md" src="{% static 'img/mark_email_read_black_48dp.svg' %}" alt="">
                </div>

                <h1>{% translate "Token Revocation Link Sent!" %}</h1>
                <div>
                    {% blocktranslate %}
                    <p>Please check your mail.<br>We've just sent you a link to a page on our site from where you can confirm the revocation of your tokens.</p>
                    <p>Kind wait for up to 4 minutes if you don't get the mail immediately.<br>And don't forget to check your spam while you're at it.</p>
                    {% endblocktranslate %}
                    <div class="jumbotron">
                        {% blocktranslate %}
                        <h2>Still did not get a mail?</h2>
                        <p>Please confirm that you <em>really</em> have an account on this site with the email you're asking that the revocation link be sent to.</p>
                        {% endblocktranslate %}
                        <div class="actions">
                            <a href="{% url 'accounts:token_revocation_url_request' %}" class="waves-effect waves-light btn">{% translate "Request revocation link, again" %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}